version: '3'
services:
  playto-web:
    build:
      context: .
    image: playto
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    networks:
      - playto

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
      - ./backup:/backup
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: playtoadmin
      MONGO_INITDB_ROOT_PASSWORD: v13g0+pr0j3ct0
    networks:
      - playto
    ports:
      - "27017:27017"

volumes:
  mongo-data:

networks:
  playto:
